package com.lovemaptually.service;
import com.lovemaptually.common.ApiException;import com.lovemaptually.dto.request.*;import com.lovemaptually.dto.response.*;import com.lovemaptually.entity.*;import com.lovemaptually.repository.*;import lombok.RequiredArgsConstructor;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.security.SecureRandom;import java.time.OffsetDateTime;import java.util.*;import static com.lovemaptually.entity.Enums.*;
@Service @RequiredArgsConstructor
public class GroupService {private static final String ALPHABET="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";private final RelationGroupRepository groups;private final GroupMemberRepository members;private final InviteCodeRepository invites;private final UserRepository users;private final AccessService access;private final SecureRandom random=new SecureRandom();
 @Transactional public GroupResponse create(long uid,CreateGroupRequest b){GroupType type;try{type=GroupType.valueOf(b.groupType().toUpperCase());}catch(Exception e){throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_GROUP_TYPE","groupType을 확인해 주세요");}assertCouple(uid,type);User user=user(uid);RelationGroup g=groups.saveAndFlush(RelationGroup.builder().groupType(type).name(b.name()).build());members.saveAndFlush(GroupMember.builder().group(g).user(user).role(MemberRole.OWNER).build());return response(g);}
 @Transactional(readOnly=true) public GroupListResponse mine(long uid){return new GroupListResponse(members.findAllByUserUserIdAndLeftAtIsNullOrderByJoinedAt(uid).stream().map(GroupMember::getGroup).map(this::response).toList());}
 @Transactional public InviteResponse invite(long uid,long gid,CreateInviteRequest b){access.member(gid,uid);int max=b.maxUses()==null?1:b.maxUses(),hours=b.expiresInHours()==null?24:b.expiresInHours();String code;do{code=randomCode();}while(invites.existsByCode(code));InviteCode i=invites.saveAndFlush(InviteCode.builder().code(code).group(group(gid)).inviter(user(uid)).status(InviteStatus.ACTIVE).maxUses(max).useCount(0).expiresAt(OffsetDateTime.now().plusHours(hours)).build());return inviteResponse(i);}
 @Transactional(readOnly=true) public InvitePreviewResponse inspect(String code){InviteCode i=invites.findByCode(code.toUpperCase()).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"INVITE_NOT_FOUND","초대 코드를 찾을 수 없습니다"));ensureAvailable(i);RelationGroup g=i.getGroup();return new InvitePreviewResponse(g.getGroupId(),g.getGroupType().name(),g.getName(),members.countByGroupGroupIdAndLeftAtIsNull(g.getGroupId()),true,i.getExpiresAt());}
 @Transactional public GroupResponse join(long uid,JoinGroupRequest b){InviteCode i=invites.findLockedByCode(b.inviteCode().toUpperCase()).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"INVITE_NOT_FOUND","초대 코드를 찾을 수 없습니다"));ensureAvailable(i);long gid=i.getGroup().getGroupId();if(members.existsByGroupGroupIdAndUserUserIdAndLeftAtIsNull(gid,uid))throw new ApiException(HttpStatus.CONFLICT,"GROUP_MEMBER_DUPLICATED","이미 그룹의 구성원입니다");assertCouple(uid,i.getGroup().getGroupType());GroupMember m=members.findByGroupGroupIdAndUserUserId(gid,uid).orElseGet(()->GroupMember.builder().group(i.getGroup()).user(user(uid)).build());m.setLeftAt(null);m.setRole(MemberRole.MEMBER);members.save(m);i.setUseCount(i.getUseCount()+1);return response(i.getGroup());}
 @Transactional(readOnly=true) public GroupResponse response(RelationGroup g){List<MemberResponse> ms=members.findAllByGroupGroupIdAndLeftAtIsNullOrderByJoinedAt(g.getGroupId()).stream().map(m->new MemberResponse(m.getUser().getUserId(),m.getUser().getNickname(),m.getRole().name(),m.getJoinedAt())).toList();return new GroupResponse(g.getGroupId(),g.getGroupType().name(),g.getName(),g.getCreatedAt(),ms);}
 private void assertCouple(long uid,GroupType type){if(type==GroupType.COUPLE&&members.countActiveType(uid,GroupType.COUPLE)>0)throw new ApiException(HttpStatus.CONFLICT,"COUPLE_GROUP_ALREADY_EXISTS","이미 커플 그룹에 속해 있습니다");}private void ensureAvailable(InviteCode i){if(i.getStatus()!=InviteStatus.ACTIVE||i.getUseCount()>=i.getMaxUses()||i.getExpiresAt().isBefore(OffsetDateTime.now()))throw new ApiException(HttpStatus.GONE,"INVITE_GONE","만료되었거나 소진된 초대 코드입니다");}
 private RelationGroup group(long id){return groups.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"GROUP_NOT_FOUND","그룹을 찾을 수 없습니다"));}private User user(long id){return users.findById(id).orElseThrow(()->new ApiException(HttpStatus.UNAUTHORIZED,"UNAUTHORIZED","인증이 필요합니다"));}private InviteResponse inviteResponse(InviteCode i){return new InviteResponse(i.getInviteCodeId(),i.getCode(),i.getMaxUses(),i.getUseCount(),i.getStatus().name(),i.getExpiresAt(),i.getCreatedAt());}private String randomCode(){StringBuilder s=new StringBuilder(8);for(int x=0;x<8;x++)s.append(ALPHABET.charAt(random.nextInt(ALPHABET.length())));return s.toString();}}
