package com.lovemaptually.service;
import com.lovemaptually.common.ApiException;import com.lovemaptually.dto.request.*;import com.lovemaptually.dto.response.*;import com.lovemaptually.entity.*;import com.lovemaptually.repository.*;import lombok.RequiredArgsConstructor;import org.springframework.data.domain.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;import static com.lovemaptually.entity.Enums.*;
@Service @RequiredArgsConstructor
public class PlaceService {private final PlaceRepository places;private final PlaceTagRepository placeTags;private final GroupPlaceRepository groupPlaces;private final RelationGroupRepository groups;private final UserRepository users;private final ReviewRepository reviews;private final AccessService access;
 @Transactional(readOnly=true) public PlaceSearchResponse search(String query,String region,int page,int size){if(query==null||query.isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,"QUERY_REQUIRED","검색어를 입력해 주세요");if(page<0||size<1||size>100)throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_PAGE","페이징 값을 확인해 주세요");Page<Place> result=places.search(query,region,PageRequest.of(page,size,Sort.by("name")));return new PlaceSearchResponse(result.map(this::response).getContent(),page,size,result.getTotalElements(),result.getTotalPages());}
 @Transactional(readOnly=true) public PlaceDetailResponse detail(long id){Place p=place(id);List<PlaceTagResponse> tags=placeTags.findAllByPlacePlaceId(id).stream().map(pt->{boolean high=pt.getFactHighCount()>=pt.getFactLowCount();return new PlaceTagResponse(pt.getTag().getName(),high?"HIGH":"LOW",high?pt.getTag().getHighLabel():pt.getTag().getLowLabel(),Math.max(pt.getFactHighCount(),pt.getFactLowCount()));}).toList();return new PlaceDetailResponse(response(p),tags);}
 @Transactional public GroupPlaceResponse add(long uid,long gid,AddGroupPlaceRequest b){access.member(gid,uid);Place p;if(b.placeId()!=null)p=place(b.placeId());else if(b.place()!=null){PlaceInput x=b.place();p=places.findByProviderAndProviderPlaceId(x.provider(),x.providerPlaceId()).orElseGet(()->new Place());p.setProvider(x.provider());p.setProviderPlaceId(x.providerPlaceId());p.setName(x.name());p.setAddress(x.address());p.setRegion(x.region());p.setCategory(x.category());p.setPriceBand(x.priceBand()==null?null:x.priceBand().shortValue());p.setLatitude(x.latitude());p.setLongitude(x.longitude());p=places.saveAndFlush(p);}else throw new ApiException(HttpStatus.BAD_REQUEST,"PLACE_REQUIRED","placeId 또는 place가 필요합니다");if(groupPlaces.existsByGroupGroupIdAndPlacePlaceId(gid,p.getPlaceId()))throw new ApiException(HttpStatus.CONFLICT,"GROUP_PLACE_DUPLICATED","이미 담은 장소입니다");GroupPlace gp=groupPlaces.saveAndFlush(GroupPlace.builder().group(groups.getReferenceById(gid)).place(p).addedBy(users.getReferenceById(uid)).reviewedCount(0).likedCount(0).build());return new GroupPlaceResponse(gp.getGroupPlaceId(),gid,p.getPlaceId(),uid,null,gp.getCreatedAt());}
 @Transactional(readOnly=true) public GroupMapResponse map(long uid,long gid,String label){access.member(gid,uid);List<GroupPlace> list;if(label==null)list=groupPlaces.findAllByGroupGroupIdOrderByCreatedAtDesc(gid);else{try{list=groupPlaces.findAllByGroupGroupIdAndLabelOrderByCreatedAtDesc(gid,PlaceLabel.valueOf(label));}catch(Exception e){throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_LABEL","label을 확인해 주세요");}}return new GroupMapResponse(list.stream().map(this::marker).toList());}
 @Transactional(readOnly=true) public PinDetailResponse pin(long uid,long gid,long pid){access.member(gid,uid);GroupPlace gp=groupPlaces.findByGroupGroupIdAndPlacePlaceId(gid,pid).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"GROUP_PLACE_NOT_FOUND","지도의 장소를 찾을 수 없습니다"));List<Review> rs=reviews.findAllByWithGroupGroupIdAndPlacePlaceIdOrderByVisitedOnDesc(gid,pid);Map<LocalDate,Long> counts=new LinkedHashMap<>();rs.forEach(r->counts.merge(r.getVisitedOn(),1L,Long::sum));List<VisitSummaryResponse> visits=counts.entrySet().stream().map(e->new VisitSummaryResponse(e.getKey(),e.getValue())).toList();List<ReviewSummaryResponse> summaries=rs.stream().map(r->new ReviewSummaryResponse(r.getReviewId(),r.getUser().getUserId(),r.getUser().getNickname(),r.getRating(),r.getContent(),r.getVisitedOn())).toList();return new PinDetailResponse(gp.getGroupPlaceId(),response(gp.getPlace()),name(gp.getLabel()),gp.getReviewedCount(),gp.getLikedCount(),gp.getLabelUpdatedAt(),visits,summaries);}
 public Place place(long id){return places.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"PLACE_NOT_FOUND","장소를 찾을 수 없습니다"));}public PlaceResponse response(Place p){return new PlaceResponse(p.getPlaceId(),p.getProvider(),p.getProviderPlaceId(),p.getName(),p.getRegion(),p.getAddress(),p.getCategory(),p.getPriceBand(),p.getLatitude(),p.getLongitude());}private MapMarkerResponse marker(GroupPlace gp){Place p=gp.getPlace();return new MapMarkerResponse(gp.getGroupPlaceId(),p.getPlaceId(),p.getName(),p.getAddress(),p.getCategory(),p.getLatitude(),p.getLongitude(),name(gp.getLabel()),gp.getReviewedCount(),gp.getLikedCount());}private String name(Enum<?> e){return e==null?null:e.name();}}
