CREATE TYPE group_type AS ENUM ('COUPLE','FAMILY','FRIENDS');
CREATE TYPE member_role AS ENUM ('OWNER','MEMBER');
CREATE TYPE invite_status AS ENUM ('ACTIVE','EXPIRED','REVOKED');
CREATE TYPE attr_level AS ENUM ('HIGH','LOW');
CREATE TYPE tag_axis AS ENUM ('ATMOSPHERE','TASTE','CONVENIENCE','PRICE','PURPOSE');
CREATE TYPE rec_status AS ENUM ('PENDING','COMPLETED','FAILED');
CREATE TYPE rec_basis AS ENUM ('OWN','OTHERS');
CREATE TYPE place_label AS ENUM ('ALL_LIKED','MIXED','ON_HOLD');

CREATE TABLE users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  nickname VARCHAR(50) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE relation_groups (
  group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_type group_type NOT NULL DEFAULT 'COUPLE', name VARCHAR(50),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE group_members (
  group_member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL REFERENCES relation_groups(group_id),
  user_id BIGINT NOT NULL REFERENCES users(user_id), role member_role NOT NULL DEFAULT 'MEMBER',
  joined_at TIMESTAMPTZ NOT NULL DEFAULT now(), left_at TIMESTAMPTZ,
  CONSTRAINT uq_group_members_pair UNIQUE(group_id,user_id)
);
CREATE INDEX ix_group_members_user ON group_members(user_id);
CREATE TABLE invite_codes (
  invite_code_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(16) NOT NULL UNIQUE, group_id BIGINT NOT NULL REFERENCES relation_groups(group_id),
  inviter_user_id BIGINT NOT NULL REFERENCES users(user_id), status invite_status NOT NULL DEFAULT 'ACTIVE',
  max_uses INTEGER NOT NULL DEFAULT 1 CHECK(max_uses > 0), use_count INTEGER NOT NULL DEFAULT 0,
  expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK(use_count >= 0 AND use_count <= max_uses)
);
CREATE INDEX ix_invite_codes_group ON invite_codes(group_id);
CREATE INDEX ix_invite_codes_inviter ON invite_codes(inviter_user_id);
CREATE TABLE places (
  place_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider VARCHAR(20) NOT NULL, provider_place_id VARCHAR(64) NOT NULL, name VARCHAR(200) NOT NULL,
  address VARCHAR(300) NOT NULL, region VARCHAR(50) NOT NULL, category VARCHAR(50) NOT NULL,
  price_band SMALLINT CHECK(price_band BETWEEN 1 AND 4), latitude NUMERIC(10,7) NOT NULL,
  longitude NUMERIC(10,7) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_places_provider UNIQUE(provider,provider_place_id)
);
CREATE INDEX ix_places_region ON places(region);
CREATE INDEX ix_places_search ON places USING gin(to_tsvector('simple', name || ' ' || address || ' ' || category));
CREATE TABLE reviews (
  review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(user_id), place_id BIGINT NOT NULL REFERENCES places(place_id),
  visited_on DATE NOT NULL, with_group_id BIGINT REFERENCES relation_groups(group_id),
  rating SMALLINT NOT NULL CHECK(rating BETWEEN 1 AND 5), content TEXT NOT NULL,
  tag_status VARCHAR(10) NOT NULL DEFAULT 'PENDING' CHECK(tag_status IN ('PENDING','COMPLETED','FAILED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_reviews_visit UNIQUE(user_id,place_id,visited_on)
);
CREATE INDEX ix_reviews_place ON reviews(place_id); CREATE INDEX ix_reviews_with_group ON reviews(with_group_id);
CREATE TABLE group_places (
  group_place_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL REFERENCES relation_groups(group_id), place_id BIGINT NOT NULL REFERENCES places(place_id),
  added_by_user_id BIGINT NOT NULL REFERENCES users(user_id), label place_label,
  reviewed_count INTEGER NOT NULL DEFAULT 0, liked_count INTEGER NOT NULL DEFAULT 0,
  label_updated_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK(liked_count >= 0 AND liked_count <= reviewed_count),
  CONSTRAINT uq_group_places_pair UNIQUE(group_id,place_id)
);
CREATE INDEX ix_group_places_place ON group_places(place_id);
CREATE TABLE tags (
  tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(20) NOT NULL UNIQUE,
  axis tag_axis NOT NULL, high_label VARCHAR(20) NOT NULL, low_label VARCHAR(20) NOT NULL
);
CREATE TABLE review_tags (
  review_tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id BIGINT NOT NULL REFERENCES reviews(review_id) ON DELETE CASCADE,
  tag_id BIGINT NOT NULL REFERENCES tags(tag_id), fact_value attr_level, want_value attr_level, evidence_text TEXT,
  CONSTRAINT uq_review_tags_pair UNIQUE(review_id,tag_id)
);
CREATE INDEX ix_review_tags_tag ON review_tags(tag_id);
CREATE TABLE place_tags (
  place_tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  place_id BIGINT NOT NULL REFERENCES places(place_id), tag_id BIGINT NOT NULL REFERENCES tags(tag_id),
  fact_high_count INTEGER NOT NULL DEFAULT 0, fact_low_count INTEGER NOT NULL DEFAULT 0,
  recomputed_at TIMESTAMPTZ NOT NULL DEFAULT now(), CONSTRAINT uq_place_tags_pair UNIQUE(place_id,tag_id)
);
CREATE INDEX ix_place_tags_tag ON place_tags(tag_id);
CREATE TABLE user_tags (
  user_tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(user_id), tag_id BIGINT NOT NULL REFERENCES tags(tag_id),
  want_high_count INTEGER NOT NULL DEFAULT 0, want_low_count INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), CONSTRAINT uq_user_tags_pair UNIQUE(user_id,tag_id)
);
CREATE INDEX ix_user_tags_tag ON user_tags(tag_id);
CREATE TABLE unmatched_tag_logs (
  log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id BIGINT NOT NULL REFERENCES reviews(review_id) ON DELETE CASCADE,
  raw_tag VARCHAR(50) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE place_similarity (
  place_similarity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  place_id BIGINT NOT NULL REFERENCES places(place_id), similar_place_id BIGINT NOT NULL REFERENCES places(place_id),
  score NUMERIC(5,4) NOT NULL CHECK(score BETWEEN -1 AND 1), computed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK(place_id <> similar_place_id), CONSTRAINT uq_place_similarity_pair UNIQUE(place_id,similar_place_id)
);
CREATE INDEX ix_place_similarity_rank ON place_similarity(place_id,score DESC);
CREATE TABLE recommendation_requests (
  request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL REFERENCES relation_groups(group_id), requested_by_user_id BIGINT NOT NULL REFERENCES users(user_id),
  query TEXT NOT NULL, intent_region VARCHAR(50), intent_count SMALLINT, intent_budget SMALLINT CHECK(intent_budget BETWEEN 1 AND 4),
  candidate_count INTEGER, cf_weight NUMERIC(3,2) CHECK(cf_weight BETWEEN 0 AND 1),
  status rec_status NOT NULL DEFAULT 'PENDING', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), completed_at TIMESTAMPTZ
);
CREATE INDEX ix_rec_requests_group ON recommendation_requests(group_id,created_at);
CREATE INDEX ix_rec_requests_user ON recommendation_requests(requested_by_user_id);
CREATE TABLE recommendations (
  recommendation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id BIGINT NOT NULL REFERENCES recommendation_requests(request_id) ON DELETE CASCADE,
  place_id BIGINT NOT NULL REFERENCES places(place_id), matched_tags TEXT[], basis rec_basis NOT NULL,
  reason TEXT NOT NULL, display_order SMALLINT NOT NULL,
  CONSTRAINT uq_recommendations_pair UNIQUE(request_id,place_id),
  CONSTRAINT uq_recommendations_order UNIQUE(request_id,display_order)
);

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END $$ LANGUAGE plpgsql;
CREATE TRIGGER users_updated BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER reviews_updated BEFORE UPDATE ON reviews FOR EACH ROW EXECUTE FUNCTION set_updated_at();
