-- UC-08 월간 리포트 (ERD v3.2). 구독 단위와 리포트 단위는 모두 그룹입니다.
CREATE TYPE report_status AS ENUM ('PENDING', 'COMPLETED', 'FAILED');

ALTER TABLE relation_groups
    ADD COLUMN plan VARCHAR(10) NOT NULL DEFAULT 'FREE';

CREATE TABLE monthly_reports (
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES relation_groups(group_id),
    report_month DATE NOT NULL,
    status report_status NOT NULL DEFAULT 'PENDING',
    model VARCHAR(50),
    prompt_tokens INTEGER,
    completion_tokens INTEGER,
    content JSONB,
    requested_by_user_id BIGINT NOT NULL REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    CONSTRAINT uq_monthly_reports_month UNIQUE (group_id, report_month)
);
CREATE INDEX ix_monthly_reports_group ON monthly_reports(group_id, created_at);

CREATE TABLE subscriptions (
    subscription_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES relation_groups(group_id),
    plan VARCHAR(10) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ended_at TIMESTAMPTZ,
    payment_ref VARCHAR(64)
);
CREATE INDEX ix_subscriptions_group ON subscriptions(group_id, started_at);
